--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/libdesign-pattern
build-by-default: true
branches:
- master
- dev/0.2-php7.3
projects:
  libdesign-pattern:
    path: ""
    type: library
    model: virion
...
